# Generated by Django 4.1 on 2022-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=125)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('describe_yourself', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.URLField(blank=True, max_length=125, null=True)),
                ('title', models.CharField(max_length=145)),
                ('demo', models.URLField(blank=True, null=True)),
                ('code', models.URLField(blank=True, null=True)),
                ('highlight', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('program', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(max_length=125)),
                ('name', models.CharField(max_length=30)),
                ('skill_range', models.PositiveIntegerField()),
            ],
        ),
    ]
