# Generated by Django 4.1 on 2022-09-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_skill_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='icon',
            new_name='class_name',
        ),
    ]
