# Generated by Django 4.1 on 2022-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_icon_skill_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
