version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:11
    restart: always
    volumes:
      - portfolio_data:/var/lib/postgresql/data/
    env_file: .env-db
    ports:
      - 5432:5432

volumes:
  portfolio_data:
    external: true